### ISSUE TITLE
Error running sampling code

### ISSUE THREAD

**Issue by ZhaoyangZh** [lukemelas/projection-conditioned-point-cloud-diffusion#6]
Hi there,

Thanks for the open source code. When I run the sampling code using the following command (which is slightly modified to what you provide in README), 

```shell
python main.py run.job=sample dataloader.batch_size=16 dataloader.num_workers=6 dataset.category=teddybear checkpoint.resume="./example-logs-and-checkpoints/train__teddybear__ebs_48/2022-09-19--16-11-43/checkpoint-latest.pth" run.name=sample__teddybear__ebs_24
```

I got this error:
```python
ValidationError: Incompatible value 'None' for field of type 'str'
    full_key: root
    object_type=CO3DConfig
```

It originates from `./experiments/config/structured.py:282`:
```python
cs.store(group='dataset', name='co3d', node=CO3DConfig)
```

Do you have any idea on this issue? Thanks in advance.

**Comment by ZhaoyangZh** [comment]
It's due to not exporting environment variable `CO3DV2_DATASET_ROOT `.

**Comment by ZhaoyangZh** [comment]
Also one more note here, the `checkpoint.resume` path should be set as absolute path, since the working directory seems to be changed during runtime.

**Comment by psen2022** [comment]
run.job=sample
dataloader.batch_size=16
dataloader.num_workers=6
dataset.category=hydrant
checkpoint.resume="/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-conditioned-point-cloud-diffusion-main/experiments/exp/logs/example-logs-and-checkpoints/train__hydrant__ebs_16/2022-09-12--09-16-11/checkpoint-latest.pth"
run.name=sample__hydrant__ebs_24                                            
After I configured this, why do I get the following error?                                                      Error executing job with overrides: ['run.job=sample', 'dataloader.batch_size=16', 'dataloader.num_workers=6', 'dataset.category=hydrant', 'checkpoint.resume=/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-conditioned-point-cloud-diffusion-main/experiments/exp/logs/example-logs-and-checkpoints/train__hydrant__ebs_16/2022-09-12--09-16-11/checkpoint-latest.pth', 'run.name=sample__hydrant__ebs_24']
Traceback (most recent call last):
  File 
"/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-co
nditioned-point-cloud-diffusion-main/experiments/main.py", line 450, in <module>
    main()
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/main.py", line
94, in decorated_main
    _run_hydra(
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/_internal/util
s.py", line 394, in _run_hydra
    _run_app(
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/_internal/util
s.py", line 457, in _run_app
    run_and_report(
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/_internal/util
s.py", line 223, in run_and_report
    raise ex
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/_internal/util
s.py", line 220, in run_and_report
    return func()
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/_internal/util
s.py", line 458, in <lambda>
    lambda: hydra.run(
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/_internal/hydr
a.py", line 132, in run
    _ = ret.return_value
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/core/utils.py"
, line 260, in return_value
    raise self._return_value
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/hydra/core/utils.py"
, line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File 
"/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-co
nditioned-point-cloud-diffusion-main/experiments/main.py", line 58, in main
    model = get_model(cfg)
  File 
"/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-co
nditioned-point-cloud-diffusion-main/experiments/model/__init__.py", line 8, in 
get_model
    model = ConditionalPointCloudDiffusionModel(**cfg.model)
  File 
"/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-co
nditioned-point-cloud-diffusion-main/experiments/model/model.py", line 31, in 
__init__
    super().__init__(**kwargs)
  File 
"/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-co
nditioned-point-cloud-diffusion-main/experiments/model/projection_model.py", 
line 64, in __init__
    self.feature_model = FeatureModel(image_size, image_feature_model)
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/diffusers/configurat
ion_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File 
"/workspace/psen/projection-conditioned-point-cloud-diffusion-main/projection-co
nditioned-point-cloud-diffusion-main/experiments/model/feature_model.py", line 
99, in __init__
    state_dict['pos_embed'] = resize_pos_embed(state_dict['pos_embed'], 
self.model.pos_embed)
  File 
"/usr/local/anaconda3/envs/psen/lib/python3.8/site-packages/timm/models/vision_t
ransformer.py", line 769, in resize_pos_embed
    posemb_grid = F.interpolate(posemb_grid, size=gs_new, mode=interpolation, 
antialias=antialias, align_corners=False)
TypeError: interpolate() got an unexpected keyword argument 'antialias'

**Comment by psen2022** [comment]
Do you have any good solutions? Thanks
